name: push

on: [push]

jobs:
  build:
    name: Quality Control
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: false

      - name: Install Go quality tools
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.1.7
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.2

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bootstrap
        run: |
          task bootstrap

      - name: Unit tests
        run: |
          # Note: it is by design that we don't use the builder
          task test:unit
      - name: Integration tests
        run: |
          # Note: it is by design that we don't use the builder
          task test:integration